### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by shrederr** [shrederr/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by RickSanchez-morty** [comment]
- https://www.facebook.com/ElAbueloRick/
- https://www.instagram.com/rickandmorty/?hl=ru
- https://twitter.com/c137ricksanchez
- ricksanchez@gmail.com
