### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by shrederr** [shrederr/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by RickSanchez-morty** [comment]
https://github.com/RickSanchez-morty , https://www.facebook.com/ElAbueloRick/ , https://twitter.com/c137ricksanchez , https://www.instagram.com/rickandmorty/?hl=ru
