### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by shrederr** [shrederr/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by RickSanchez-morty** [comment]
https://www.facebook.com/ElAbueloRick/ https://github.com/RickSanchez-morty skype:Rick-szechuanSauce tel:+73228toyourass
