### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by shrederr** [shrederr/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by RickSanchez-morty** [comment]
**LANGUAGES**

🇺🇸 ENGLISH  🇷🇺 РУССКИЙ

**SKILLS**

SCIENCE CAN DO EVERYTHING SO I CAN DO EVERYTHING.

**СHARACTER**

SKEPTIC EXTREMELY CYNICAL GROUCHY BUT NOT WITHOUT A SENSE OF HUMOR MOSTLY BLACK.

**LIKES**

😻 SZECHUAN SAUCE

😵 WATCH INTERGALACTIC TV

😶 MY THRONE OF LONELINESS(P.S WC) ON ANOTHER PLANET

**DISLIKES**

When my daughter tries to kill me and EVERYTHING ELSE...

**WANTS**

FIND SZECHUAN SAUCE

**AWARDS**

EMMY AWARDS 2018

IGN PEOPLE’S CHOICE AWARD 2017

IGN AWARDS 2017
