### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by shrederr** [shrederr/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by RickSanchez-morty** [comment]
**THE PURPOSE OF LIFE**

Destroy the whole universe to find szechuan sauce

**SKILLS**

Science can do everything so I can do everything.

**LIFE LESSON**

Listen, Morty, I hate to break it to you but what people call "love" is just a chemical reaction that compels animals to breed. It hits hard, Morty, then it slowly fades, leaving you stranded in a failing marriage. I did it. Your parents are gonna do it. Break the cycle, Morty. Rise above. Focus on science.

**LIKES**

- Szechuan sauce
- Watch intergalactic tv
- My throne of loneliness(p.s WC) on another planet

**DISLIKES**
- Everything else
